add_newline=false
command_timeout=1000

[conda]
disabled=true

[crystal]
disabled=true

[dart]
disabled=true

[deno]
disabled=true

[elixir]
disabled=true

[elm]
disabled=true

[erlang]
disabled=true

[gcloud]
disabled=true

[git_branch]
format="[$symbol$branch]($style) "

[java]
format="[${symbol}(${version} )]($style)"

[julia]
disabled=true

[line_break]
disabled=true

[ocaml]
disabled=true

[package]
disabled=true

[red]
disabled=true

[scala]
disabled=true

[singularity]
disabled=true

[vlang]
disabled=true

[vcsh]
disabled=true
